ambar:
  mq:
    channel.seguridad.channelName: BK.SEG.EVENTS.SVC
    channel.seguridad.queueManager: BKSUN.INT.WF
    channel.seguridad.QueueName.Env: BK.SEG.EVENTS.ENV
    channel.seguridad.QueueName.Rec: BK.SEG.EVENTS.REC
    channel.seguridad.cachingConnection: true
    channel.seguridad.concurrency: 3-10
    channel.seguridad.receiveTimeout: 3
    channel.seguridad.explicitQosEnabled: true
    channel.seguridad.deliveryMode: 2
    channel.seguridad.sessionAcknowledgeModeName: AUTO_ACKNOWLEDGE
    channel.seguridad.sessionTransacted: true
    channel.seguridad.pubSubDomain: false
    cachingConnection: false
    clientReconnectTimeout: 7
  manifest:
    required:
      datasources: ms

  datasource:
    ms:
      packagesToScan: com.bankinter.services.pos.ais.ambar.entity
psd2:
  ais:
    pageSize: 7
    tx:
      BF25:
        producto: TRF
        grupoProducto: A
      YG03:
        producto: CCR
        grupoProducto: CTA
      YG04:
        producto: CCR
        grupoProducto: CTA
      YG05:
        producto: CCR
        grupoProducto: CTA
